### ISSUE TITLE
Zobrazovanie matiky

### ISSUE THREAD

**Issue by lukaskogaborik** [trojsten/web#1400]
Na mobile (resp. malej obrazovke) sa matické výrazy useknú:
![image](https://user-images.githubusercontent.com/38594139/155845399-30182884-0603-46c1-808e-4ff634b2ab47.png)
Asi by bolo fajn, aby sa v takomto prípade pod nimi objavil scrollbar:
![image](https://user-images.githubusercontent.com/38594139/155845412-15b02bd2-5177-4fbe-a746-ec749ffcacde.png)
Takéto niečo by to malo byť schopné vyriešiť:
```css
.MathJax_Display {
  overflow-y: hidden; /*creates x-scroll for display math when necessary*/
}
```
